server:
  port: 8050
spring:
  application:
    name: hyh-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhan/micro-cloud/config
          username: woshizw
          password: zhan2018
eureka:
  #instance:
     #preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://106.12.11.54:8761/eureka/,http://106.12.11.54:8762/eureka/